//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace air_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.Purchases = new HashSet<Purchases>();
        }
    
        public int IdCard { get; set; }
        public string CardNumber { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string CW_CVC { get; set; }
        public string OwnerName { get; set; }
        public int IdUser { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }

        public Card(string cardNumber, string month, string year, string cW_CVC, string ownerName, int idUser)
        {
            CardNumber = cardNumber;
            Month = month;
            Year = year;
            CW_CVC = cW_CVC;
            OwnerName = ownerName;
            IdUser = idUser;
        }
    }
}
