//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace air_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public long IdCard { get; set; }
        public string Month { get; set; }
        public int Year { get; set; }
        public int CW_CVC { get; set; }
        public string Name { get; set; }
        public string IdCustomer { get; set; }
    
        public virtual User User { get; set; }
    }
}
