//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace air_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Purchases_Ticket = new HashSet<Purchases_Ticket>();
        }
    
        public int IdDocument { get; set; }
        public int IdType { get; set; }
        public string Number { get; set; }
        public int IdPassenger { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Type_Document Type_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases_Ticket> Purchases_Ticket { get; set; }

        public Document(int idType, string number, int idPassenger)
        {
            IdType = idType;
            Number = number;
            IdPassenger = idPassenger;
        }
    }
}
