//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace air_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int IdDocument { get; set; }
        public int IdCustomer { get; set; }
        public int IdType { get; set; }
        public int Series { get; set; }
        public int Number { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Type_Document Type_Document { get; set; }
    }
}
