//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace air_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchases()
        {
            this.Purchases_Ticket = new HashSet<Purchases_Ticket>();
        }
    
        public int IdPurchases { get; set; }
        public int IdCard { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int TotalCost { get; set; }
    
        public virtual Card Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases_Ticket> Purchases_Ticket { get; set; }

        public Purchases(int idCard, DateTime purchaseDate, int totalCost)
        {
            IdCard = idCard;
            PurchaseDate = purchaseDate;
            TotalCost = totalCost;
        }
    }
}
