//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace air_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases_Ticket
    {
        public int IdTicket { get; set; }
        public int IdPurchases { get; set; }
        public int IdDocument { get; set; }
        public int IdPurchases_Ticket { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Purchases Purchases { get; set; }
        public virtual Ticket Ticket { get; set; }

        public Purchases_Ticket() { }

        public Purchases_Ticket(int idTicket, int idPurchases, int idDocument)
        {
            IdTicket = idTicket;
            IdPurchases = idPurchases;
            IdDocument = idDocument;
        }
    }
}
